apiVersion: microcks.io/v1alpha1
kind: Microcks
metadata:
  name: microcks
  namespace: microcks
spec:
  version: 1.12.1
  microcks:
    url: microcks.127.0.0.1.sslip.io
  keycloak:
    enabled: true
    url: keycloak.127.0.0.1.sslip.io
    privateUrl: http://keycloak-keycloakx-http.default.svc.cluster.local
    install: false
    realm: microcks
    serviceAccount: microcks-serviceaccount
    serviceAccountCredentials: ab54d329-e435-41ae-a900-ec6b3fe15c54

  features:
    aiCopilot:
      enabled: false
      implementation: openai
      openai:
        apiKey: ""
        timeout: 30
        model: gpt-3.5-turbo
        maxTokens: 2000
